engines:
  duplication:
      enabled: false
      checks:
        Similar code:
          enabled: false
      config:
        languages:
          - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "server/*.js"
    - "server/**/*.js"
  exclude_paths:
    - test/
    - __test__/
    - node_modules/
    - bower_components/
    - client/dist/
