sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database postit_test;' -U postgres
  - psql -c "create user joe1 with password '1234';" -U postgres
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli

