sudo: required
dist: trusty
language: node_js
node_js:
  - "9.4.0"
services:
  - postgresql
before_script:
  - psql -c 'create database postit_test;' -U postgres
  - psql -c "create user joe1 with password '1234';" -U postgres

