language: node_js
node_js:
  - "6.11.0"
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database postit;' -U postgres
  - psql -c 'create database postit_test;' -U postgres
  - psql -c "CREATE USER joe1 WITH PASSWORD '1234';" -U postgres 
script:
  - npm install
  - npm run migrations
  - npm test
after_success: 
  - npm run coverage
  - npm run coveralls
