language: node_js
node_js:
  - "6.11.0"
services:
  - postgresql
before_script:
  - psql -c 'create database postit;' -U postgres
  - psql -c "CREATE USER joe1 WITH PASSWORD '1234';" -U postgres  
  - sequelize db:migrate
script: npm run coverage
after_success: 'npm run coveralls'
