language: node_js
branches:
  only:
    - development
node_js:
  - "6.11.0"
# Disable email notifications
notifications:  
  email: false 
services:
  - postgresql
cache:
  - npm install
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database postit_test;' -U postgres
  - psql -c "create user joe1 with password '1234';" -U postgres 
script:
  - npm install
  - npm run migrations
  - npm test
  # - npm run-script test-on-travis
after_script:
  - npm run coveralls
after_success: 
  - npm run coverage
  

