export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_USER_GROUPS = 'SET_USER_GROUPS';
export const SET_SELECTED_GROUP = 'SET_SELECTED_GROUP';
export const SET_GROUP_MESSAGES = 'SET_GROUP_MESSAGES';
export const POST_NEW_MESSAGE = 'POST_NEW_MESSAGE';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';
