export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
