import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import SigninForm from './SigninForm';
import { userSigninRequest } from '../../actions/signin';
import { addFlashMessage } from '../../actions/flashMessage';
import FlashMessageList from '../flash-message/FlashMessagesList';


/**
 * SignIn Page Component
 * Child components: FlashMessageList and SigninForm
 */
class SignIn extends React.Component {

  /**
   * Render
   * @returns {ReactElement} SignIn page markup
   */
  render() {
    const { userSigninRequest, addFlashMessage } = this.props;
    return (
      <div className="background">
        <div className="container">
          <div className="row">
            <div className="card-panel col s12 m8 offset-m2 l6 offset-l3 z-depth-5 signin-card">
              <header className="auth-header">
                <h5 className="center">Sign In | Post It</h5>
              </header>

              <FlashMessageList/>

              <SigninForm userSigninRequest={userSigninRequest} addFlashMessage={addFlashMessage}/>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

/**
 * Maps action creators to redux dispatch function
 * Action creators bound will be available as props in Sidebar
 * Actions generated by the action creators flows though all the reducers
 * @param {function} dispatch Redux dispatch function
 * @returns {function} Action cretaors bound to redux dispatch function
 */
function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    userSigninRequest,
    addFlashMessage
  }, dispatch);
}

SignIn.propTypes = {
  userSigninRequest: PropTypes.func.isRequired,
  addFlashMessage: PropTypes.func.isRequired
};

export default connect(null, mapDispatchToProps)(SignIn);
