import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

import SignupForm from './SignupForm';
import { userSignupRequest } from '../../actions/signup';
import { userSigninRequest } from '../../actions/signin';

/**
 * SignUp Page Component
 * Child components: SignupForm.js
 */
class SignUp extends React.Component {

  /**
   * Render
   * @returns {ReactElement} SignUp page markup
   */
  render() {
    const { userSignupRequest, userSigninRequest } = this.props;
    return (
      <div className="background">
        <div className="container">
          <div className="row">
            <div className="card-panel col s12 m8 offset-m2 l6 offset-l3 z-depth-5 signup-panel">
              <header className="auth-header">
                <h5 className="center">Sign up | Post It</h5>
              </header>

              <SignupForm
                userSignupRequest={userSignupRequest}
                userSigninRequest={userSigninRequest}
              />
            </div>
          </div>
        </div>
      </div>
    );
  }
}

/**
 * Maps action creators to redux dispatch function
 * Action creators bound will be available as props in Sidebar
 * Actions generated by the action creators flows though all the reducers
 * @param {function} dispatch Redux dispatch function
 * @returns {function} Action cretaors bound to redux dispatch function
 */
function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    userSignupRequest,
    userSigninRequest
  }, dispatch);
}

SignUp.propTypes = {
  userSignupRequest: PropTypes.func.isRequired,
  userSigninRequest: PropTypes.func.isRequired
};


export default connect(null, mapDispatchToProps)(SignUp);
