import React from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import PropTypes from 'prop-types';
import { postNewMessage } from '../../actions/groupMessagesAction';

/**
 * Message Input Form component for message board
 */
class MsgForm extends React.Component {
  /**
   * Constructor
   * @param {object} props
   */
  constructor(props) {
    super(props);

    this.state = {
      messageInput: '',
      errors: {}
    };

    this.onChange = this.onChange.bind(this);
    this.onMessageSend = this.onMessageSend.bind(this);
  }

  /**
   * Handles change event of New Group input form
   * Updates messageInput state
   * @param {SyntheticEvent} e
   * @returns {void}
   */
  onChange(e) {
    this.setState({ [e.target.name]: e.target.value });
  }


  /**
   * Handles Message Send event
   * Dispatches PostNewMessage action if a group exists and message is not empty
   * @param {SyntheticEvent} e
   * @returns {void}
   */
  onMessageSend(e) {
    e.preventDefault();
    const { groupId, userId } = this.props;
    if (groupId && this.state.messageInput !== '') {
      this.props.postNewMessage({
        message: this.state.messageInput,
        group_id: groupId
      }).then(() => {
        this.setState({ messageInput: '' });
      });
    }
  }

  /**
   * Render
   * @returns {ReactElement} Message Input Form markup
   */
  render() {
    return (
      <footer className="footer">
        <div className="footer-container">
          <form className="form-horizontal">
            <div className="form-group">
              <div className="col-lg-11 col-md-10 col-sm-11 col-xs-11">
                <input
                  className="form-control"
                  type="text"
                  name="messageInput"
                  value={this.state.messageInput}
                  onChange={this.onChange}
                  placeholder="Enter your message..."
                />
              </div>

              <div className="col-lg-1 col-md-2 col-sm-1 col-xs-1 msg-send-btn">
                <a
                  href='#'
                  type="submit"
                  onClick={this.onMessageSend}
                  className="btn waves-effect waves-light blue lighten-1">
                  Send
                </a>
              </div>
            </div>
          </form>
        </div>
      </footer>
    );
  }
}


/**
 * Maps pieces of the redux state to props
 * @param {object} state Redux state
 * @returns {object} User id and selected group id
 */
function mapStateToProps(state) {
  return {
    groupId: state.selectedGroup.id,
    userId: state.signedInUser.id
  };
}


/**
 * Maps action creators to redux dispatch function
 * Action creators bound will be available as props in Sidebar
 * Actions generated by the action creators flows though all the reducers
 * @param {function} dispatch Redux dispatch function
 * @returns {function} Action cretaors bound to redux dispatch function
 */
function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    postNewMessage
  }, dispatch);
}


MsgForm.propTypes = {
  userId: PropTypes.number,
  groupId: PropTypes.number,
  postNewMessage: PropTypes.func.isRequired
};

export default connect(mapStateToProps, mapDispatchToProps)(MsgForm);
